travis:
  secure:
    BINSTAR_TOKEN: KsR9hBQoGCQOdKYpnCJ/Ippxkqq/RzQEDqL83bulzZoIPgwLizOaCjm/wlS/0bugojY56e13dX+2CnLudpNjl7r/srJODiCINyFLeU7lBOKTc8ePv99aSJXoI2SASe6XkGemV9gX+m7UEqiGNnmNkb67bN5aq6AhgXmUI2LwtKwTlqMytUBHZ58/k9X9Z83cAyhBpzUQoaU+flvpqf0gssbkkU5HIqEUwKwS+cwRLodOtBw1EkLH/uuIFgPuIK2+YbGRD1HmEsrFnJbsoyi6prYRhZRY4772ACrDaQUQxnTjULHMS1SJEJ4oKD/eiaVFwDl1jw6R/C0YNGZBApEpRuPEx4TT+2RBvYoPaC9Me+Z0QHgcCan2YTv3+qhC6u3dtqID3ka+MkykZor5EwfRl9x4E5RvT0FGHnfMGxfX4ClM6/c6N+l+MXWS2SOoOw4XoneJesyvGz/b8d27/TDgQ/kLE8HZMR9f3kEvA9ZxIriYuZwvVi3H3WaQW8xwVIVhuoIyW1lgteqvpULYXfrJ1Xdbm5dgoUoQ9anqU5k0crJ27w6iIza5D/1qHEZ7nG9bNrAjgQ186YZOSJRw4mwlFekT6IPNLXmcE7TCIFraQfjVqN1V00AFJy0oHiqmGS0Nvelt/LwPrDIZaxR03cs7uWjCGXISl/FkVqxcn1OkNgQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
